package lab4_2blazedemo;
/*generated by Selenium IDE without any changes 
// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class BlazeDemoTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new FirefoxDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void untitled() {
    driver.get("https://blazedemo.com/");
    driver.findElement(By.name("fromPort")).click();
    {
      WebElement dropdown = driver.findElement(By.name("fromPort"));
      dropdown.findElement(By.xpath("//option[. = 'Portland']")).click();
    }
    driver.findElement(By.cssSelector(".form-inline:nth-child(1) > option:nth-child(4)")).click();
    driver.findElement(By.name("toPort")).click();
    {
      WebElement dropdown = driver.findElement(By.name("toPort"));
      dropdown.findElement(By.xpath("//option[. = 'Cairo']")).click();
    }
    driver.findElement(By.cssSelector(".form-inline:nth-child(4) > option:nth-child(7)")).click();
    driver.findElement(By.cssSelector(".btn-primary")).click();
    driver.findElement(By.cssSelector("tr:nth-child(3) .btn")).click();
    driver.findElement(By.id("inputName")).click();
    driver.findElement(By.id("inputName")).sendKeys("Tiago Cruz");
    driver.findElement(By.id("address")).click();
    driver.findElement(By.id("address")).sendKeys("420 Duck Street");
    driver.findElement(By.id("city")).click();
    driver.findElement(By.id("city")).sendKeys("Lutontown");
    driver.findElement(By.id("state")).click();
    driver.findElement(By.id("state")).sendKeys("Rabbit");
    driver.findElement(By.id("zipCode")).click();
    driver.findElement(By.id("zipCode")).sendKeys("420");
    driver.findElement(By.id("cardType")).click();
    {
      WebElement dropdown = driver.findElement(By.id("cardType"));
      dropdown.findElement(By.xpath("//option[. = 'Diner\'s Club']")).click();
    }
    driver.findElement(By.cssSelector("option:nth-child(3)")).click();
    driver.findElement(By.id("creditCardNumber")).click();
    driver.findElement(By.id("creditCardNumber")).sendKeys("1826786921420");
    driver.findElement(By.id("creditCardMonth")).click();
    driver.findElement(By.id("creditCardMonth")).sendKeys("4");
    driver.findElement(By.id("creditCardYear")).click();
    driver.findElement(By.id("creditCardYear")).sendKeys("2100");
    driver.findElement(By.id("nameOnCard")).click();
    driver.findElement(By.id("nameOnCard")).sendKeys("Tiago Cruz");
    driver.findElement(By.cssSelector(".btn-primary")).click();
  }
}
*/

import io.github.bonigarcia.seljup.SeleniumJupiter;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.openqa.selenium.By;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.firefox.FirefoxDriver;

@ExtendWith(SeleniumJupiter.class)
public class BlazeDemoTest {

    @Test
    public void bookFlightTest(FirefoxDriver driver) {
        driver.get("https://blazedemo.com/");
        driver.findElement(By.name("fromPort")).click();
        WebElement fromPortDropdown = driver.findElement(By.name("fromPort"));
        fromPortDropdown.findElement(By.xpath("//option[. = 'Portland']")).click();
        
        driver.findElement(By.name("toPort")).click();
        WebElement toPortDropdown = driver.findElement(By.name("toPort"));
        toPortDropdown.findElement(By.xpath("//option[. = 'Cairo']")).click();
        
        driver.findElement(By.cssSelector(".btn-primary")).click();
        driver.findElement(By.cssSelector("tr:nth-child(3) .btn")).click();
        
        driver.findElement(By.id("inputName")).sendKeys("Tiago Cruz");
        driver.findElement(By.id("address")).sendKeys("420 Duck Street");
        driver.findElement(By.id("city")).sendKeys("Lutontown");
        driver.findElement(By.id("state")).sendKeys("Rabbit");
        driver.findElement(By.id("zipCode")).sendKeys("420");
        
        driver.findElement(By.id("cardType")).click();
        WebElement cardTypeDropdown = driver.findElement(By.id("cardType"));
        cardTypeDropdown.findElement(By.xpath("//option[. = \"Diner's Club\"]")).click();
        
        driver.findElement(By.id("creditCardNumber")).sendKeys("1826786921420");
        driver.findElement(By.id("creditCardMonth")).sendKeys("4");
        driver.findElement(By.id("creditCardYear")).sendKeys("2100");
        driver.findElement(By.id("nameOnCard")).sendKeys("Tiago Cruz");
        driver.findElement(By.cssSelector(".btn-primary")).click();
        
    }
}
